### ISSUE TITLE
Indigo Release

### ISSUE THREAD

**Issue by mitchellwills** [tork-a/rwt_ros#12]
Is there anything blocking releasing for indigo?

**Comment by 130s** [comment]
By `Release` do you mean to create `DEB`? If so, we haven't even done so in Hydro or backward. Whether we make a DEB or not is still in question [discussed here](https://github.com/tork-a/rwt_ros/issues/4#issuecomment-41493170).

For getting `rwt_ros` run on Indigo, AFAIK nothing blocks with the source. In fact we're just about to resume the development of `rwt_ros` and `visualization_rwt` packages so there might be some inconsistency between the upstream dependency (i.e. `RobotWebTools` etc.)

**Comment by mitchellwills** [comment]
Ok thanks
