### ISSUE TITLE
Consider merging web-related repositories under tork-a

### ISSUE THREAD

**Issue by 130s** [tork-a/rwt_ros#2]
@garaemon @KazutoMurase 

今 web 関連 repo が四つもあります．

```
tork-a
|- 1. visualization_rwt
|- 2. rwt_apps
|- 3. rwt_ros
|- 4. roswww_pkg
```

内容をよく把握してませんが，整理できる気がします．例えば，1 と 2，3 と 4 を一緒にして以下のようにできるんじゃないでしょうか．

```
tork-a
|- visualization_rwt (incl. rwt_apps)
|- rwt_ros (incl. roswww_pkg)
```

Might be related to #1 too.

**Comment by garaemon** [comment]
遅れました。

rwt_appsはいりませんね。

roswww_pkgはいかしておいて、rwt_rosからroswwwを削除したい感じですか?

-- ryohei

**Comment by 130s** [comment]
On Nov 25, 2013 12:31 PM, "garaemon" notifications@github.com wrote:

> rwt_appsはいりませんね。

では visualization_rwt に統合します．

> roswww_pkgはいかしておいて、rwt_rosからroswwwを削除したい感じですか?

いや，むしろ roswww は rwt_ros に統合して， 暫定措置でしかない roswww_pkg は削除したいです．

**Comment by garaemon** [comment]
roswww_pkgとrwt_ros/roswwwの違いは何かあるのでしょうか?

rwt_appsは消します

-- ryohei

**Comment by 130s** [comment]
あ，branch をダウンロードしたいのでちょっと待ってください

## 

Isao Isaac Saito from Android

**Comment by garaemon** [comment]
Sorry, I've just deleted rwt_apps...

-- ryohei

2013/11/26 Isaac Isao Saito notifications@github.com

> あ，branch をダウンロードしたいのでちょっと待ってください
> 
> ## 
> 
> Isao Isaac Saito from Android

**Comment by 130s** [comment]
`rwt_apps` は手元に残ってました．`rwt_moveit` を `visualization_rwt` に push します．

> roswww_pkgとrwt_ros/roswwwの違いは何かあるのでしょうか?

`rwt_ros/roswww` が見当たらない気がしますが，どこにあります？

`roswww_pkg/roswww` は，`webserver.py` という，内部で `tornado` を呼ぶスクリプトがあるのみです．
https://github.com/jihoonl/roswww から `src` を削除しただけ (あと少しだけ refactoring 中)
の版です．

もし `rwt_ros/roswww` は未だ存在しないのであれば，とりあえず `roswww_pkg/roswww` をそこに add
したいです．その後の拡張もそれに加えてもらうと．どうでしょう？

**Comment by garaemon** [comment]
ああ、失礼

roswwwはrwt_rosの管理外でした

rwt_ros以下にroswwwを移動しますか?

僕は異存ありません

-- ryohei

2013/11/27 Isaac Isao Saito notifications@github.com

**Comment by 130s** [comment]
- [Added rwt_ros/roswww](https://github.com/tork-a/rwt_ros/commit/e016ee99e028887e55183ee0ba858716a6de285c)
- [Added visualization_rwt/rwt_moveit](bdd862e27a14672f0da07914a4e54a497a96eda1)

@KazutoMurase まずければ reopen してください．
