### ISSUE TITLE
Catkinize and release rwt_ros?

### ISSUE THREAD

**Issue by 130s** [tork-a/rwt_ros#4]
#3 への回答次第ですが，もし `rwt` を ROS package として wrap したもの，ということであれば，catkinize してリリースする流れでしょうか？

**Comment by garaemon** [comment]
@furushchev working on this issue

**Comment by 130s** [comment]
> @furushchev working on this issue

Nice!

[As I just responded to rwt community](https://groups.google.com/d/msg/robot-web-tools/GQdaqbvoyuU/7EV02L8YF-kJ), however, I thought reling on more standard way to provide `.js` files (ie. `CDN` in their way) and to start a webserver (ie. [python's web server](https://github.com/tork-a/rwt_ros/issues/1#issuecomment-41492501)) sounds convincing enough to me not to release `.deb`. 

My only concern at the moment is to how to synchronize .js files, periodically if under unreliable internet, as I also asked in the response above.

Thoughts?

**Comment by aginika** [comment]
Is the catkinizing is done?

In summary, this package will not be released as deb. Is that right?

**Comment by 130s** [comment]
> Is the catkinizing is done?

I haven't heard anything from anyone.

> In summary, this package will not be released as deb. Is that right?

As I commented above I'm leaning toward no-DEB. This month we'll have a person dedicatedly work on rwt_ros, so we can discuss more in detail. Meanwhile, if you @aginika could continue catkinizing that'll be great.

**Comment by aginika** [comment]
> > This month we'll have a person dedicatedly work on rwt_ros

That's good news!

> > if you @aginika could continue catkinizing that'll be great.

I would do when I can.

**Comment by 130s** [comment]
Done in #11
