### ISSUE TITLE
error for installing rwt_ros

### ISSUE THREAD

**Issue by YoheiKakiuchi** [tork-a/rwt_ros#7]
$ git clone --recursive https://github.com/tork-a/rwt_ros.git
Cloning into 'rwt_ros'...
remote: Counting objects: 99, done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 99 (delta 35), reused 96 (delta 32)
Unpacking objects: 100% (99/99), done.
Submodule 'mjpegcanvas/www/mjpegcanvas' (https://github.com/WPI-RAIL/mjpegcanvasjs.git) registered for path 'mjpegcanvas/www/mjpegcanvas'
Submodule 'ros2djs/www/ros2djs' (https://github.com/RobotWebTools/ros2djs.git) registered for path 'ros2djs/www/ros2djs'
Submodule 'ros3djs/www/ros3djs' (https://github.com/RobotWebTools/ros3djs.git) registered for path 'ros3djs/www/ros3djs'
Submodule 'roslibjs/www/roslibjs' (https://github.com/RobotWebTools/roslibjs.git) registered for path 'roslibjs/www/roslibjs'
Cloning into 'mjpegcanvas/www/mjpegcanvas'...
remote: Counting objects: 284, done.
remote: Compressing objects: 100% (162/162), done.
remote: Total 284 (delta 122), reused 268 (delta 108)
Receiving objects: 100% (284/284), 219.14 KiB | 164 KiB/s, done.
Resolving deltas: 100% (122/122), done.
fatal: reference is not a tree: c6e5f97a05a524f25eda36a09e83d017d3125deb
Cloning into 'ros2djs/www/ros2djs'...
remote: Counting objects: 400, done.
remote: Compressing objects: 100% (202/202), done.
remote: Total 400 (delta 180), reused 378 (delta 162)
Receiving objects: 100% (400/400), 148.91 KiB | 63 KiB/s, done.
Resolving deltas: 100% (180/180), done.
Submodule path 'ros2djs/www/ros2djs': checked out '0257640ea8ec05d41310bd48912615309c55f095'
Cloning into 'ros3djs/www/ros3djs'...
remote: Counting objects: 1978, done.
remote: Compressing objects: 100% (885/885), done.
remote: Total 1978 (delta 1132), reused 1886 (delta 1048)
Receiving objects: 100% (1978/1978), 2.53 MiB | 439 KiB/s, done.
Resolving deltas: 100% (1132/1132), done.
fatal: reference is not a tree: 73e731b37b7883b6b0c98d184cecbfb58f0db4bd
Cloning into 'roslibjs/www/roslibjs'...
remote: Counting objects: 1286, done.
remote: Compressing objects: 100% (446/446), done.
remote: Total 1286 (delta 843), reused 1262 (delta 819)
Receiving objects: 100% (1286/1286), 404.61 KiB | 251 KiB/s, done.
Resolving deltas: 100% (843/843), done.
fatal: reference is not a tree: 07f3fb5d7ac3d661b48b8a133fe8ffca998fb0b3
Unable to checkout 'c6e5f97a05a524f25eda36a09e83d017d3125deb' in submodule path 'mjpegcanvas/www/mjpegcanvas'
Unable to checkout '73e731b37b7883b6b0c98d184cecbfb58f0db4bd' in submodule path 'ros3djs/www/ros3djs'
Unable to checkout '07f3fb5d7ac3d661b48b8a133fe8ffca998fb0b3' in submodule path 'roslibjs/www/roslibjs'

**Comment by garaemon** [comment]
fixed by `git reset --hard` on each submodule directory.
