### ISSUE TITLE
roswww does not have manifest.xml

### ISSUE THREAD

**Issue by kochigami** [tork-a/rwt_ros#9]
@130s 
roswww under rwt_ros does not have manifest.xml so we cannot find that package on groovy/rosbuild environment.

**Comment by 130s** [comment]
[It actually exists](https://github.com/tork-a/rwt_ros/blob/groovy-devel/roswww/manifest.xml), in `groovy-devel` branch. Current default branch is `hydro-devel` where we don't plan to maintain `rosbuild` manner.
